FROM python:3.14-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

# To Build

## docker build -t username/novamp3vX.X --no-cache

# To Tag

## docker images
## docker tag <local-image-id> username/repository-name:vX.X

# Push

## docker push username/repository-name:vX.X